-- FriendChat database setup for Supabase
-- Run this whole file in Supabase SQL Editor.
-- Safe to re-run: every statement is idempotent.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'User',
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  created_at timestamptz not null default now()
);

-- ---------- New columns for photos/videos, voice notes, and profile pictures ----------

alter table public.profiles add column if not exists avatar_url text;

alter table public.messages add column if not exists media_url text;
alter table public.messages add column if not exists media_type text;

alter table public.messages
  drop constraint if exists messages_media_type_check;
alter table public.messages
  add constraint messages_media_type_check
  check (media_type is null or media_type in ('image', 'video', 'audio'));

-- A message must have text, or a media attachment (or both).
alter table public.messages
  drop constraint if exists messages_body_check;
alter table public.messages
  add constraint messages_body_check
  check (
    (media_url is not null) or (char_length(body) between 1 and 2000)
  );

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

drop policy if exists "profiles readable by authenticated users" on public.profiles;
create policy "profiles readable by authenticated users"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "users can insert own profile" on public.profiles;
create policy "users can insert own profile"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "messages readable by authenticated users" on public.messages;
create policy "messages readable by authenticated users"
on public.messages for select
to authenticated
using (true);

drop policy if exists "users can send messages as themselves" on public.messages;
create policy "users can send messages as themselves"
on public.messages for insert
to authenticated
with check (user_id = auth.uid());

-- Automatically create a profile whenever a new auth account is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Enable realtime for both tables (skip any table already added).
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'profiles'
  ) then
    alter publication supabase_realtime add table public.profiles;
  end if;
end $$;

-- ---------- Storage: buckets for chat media and profile pictures ----------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('chat-media', 'chat-media', true, 52428800, null)
on conflict (id) do update
  set public = true, file_size_limit = 52428800, allowed_mime_types = null;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', true, 8388608, null)
on conflict (id) do update
  set public = true, file_size_limit = 8388608, allowed_mime_types = null;

-- Anyone signed in can view files (buckets are also public, so URLs work directly).
drop policy if exists "chat-media public read" on storage.objects;
create policy "chat-media public read"
on storage.objects for select
to public
using (bucket_id = 'chat-media');

drop policy if exists "avatars public read" on storage.objects;
create policy "avatars public read"
on storage.objects for select
to public
using (bucket_id = 'avatars');

-- Users may only upload into their own "<user_id>/..." folder.
drop policy if exists "chat-media insert own folder" on storage.objects;
create policy "chat-media insert own folder"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'chat-media'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "avatars insert own folder" on storage.objects;
create policy "avatars insert own folder"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- Users may only replace/delete files inside their own folder (needed for
-- avatar re-uploads which use upsert).
drop policy if exists "chat-media modify own folder" on storage.objects;
create policy "chat-media modify own folder"
on storage.objects for update
to authenticated
using (bucket_id = 'chat-media' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'chat-media' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatars modify own folder" on storage.objects;
create policy "avatars modify own folder"
on storage.objects for update
to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text)
with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "chat-media delete own folder" on storage.objects;
create policy "chat-media delete own folder"
on storage.objects for delete
to authenticated
using (bucket_id = 'chat-media' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "avatars delete own folder" on storage.objects;
create policy "avatars delete own folder"
on storage.objects for delete
to authenticated
using (bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text);
